### ISSUE TITLE
Improvements to tagging

### ISSUE THREAD

**Issue by sergimasot** [dmitrijkir/mattermost-plugin-calendar#20]
It would be great if there were a way to tag everyone in the channel automatically, for example by making it default when selecting the channel, or adding them with a simple tag like @all.

Alternatively, we could be able to select multiple users at once, since writing @ shows all the users and it's fast to click a few if the selector stays open.

**Comment by mofeing** [comment]
Would it be difficult to implicitly tagging all the members of a channel when the channel is selected when creating an event? I think this would be the most intuitive thing.

**Comment by dmitrijkir** [comment]
I'm not sure which is the right way. Often we have a global channel where everyone stays. And for example, you want to make an event for some members. I think the notification should go to only the people who were at the event. For me it is working like required members, but all in this channel can connect, if they want.

I think, better way to add tags like "@all", "@here", "@channel"

**Comment by dmitrijkir** [comment]
In the new release, a feature has been added that allows importing people from the channel. Closing the issue.
https://github.com/dmitrijkir/mattermost-plugin-calendar/releases/tag/0.5.0
