### ISSUE TITLE
Plugin doesn't show up as installed

### ISSUE THREAD

**Issue by champsupertramp** [dmitrijkir/mattermost-plugin-calendar#28]
Hi @dmitrijkir 

Thank you for your service!

1. I just installed the release archived file to /opt/mattermost/plugins and extracted the directory `com.dmkir.calendar`.
2. When I check it in the System Console > Plugins > Plugin Management  > Installed plugins, it doesn't show any installed plugins.
<img width="932" alt="Screenshot 2024-09-12 at 5 39 54 PM" src="https://github.com/user-attachments/assets/ae436e9f-f6b8-4573-a3bf-e059ef1955a8">

```
Mattermost:
Version: 9.11.1
Build Number: 10419911144
Build Date: Fri Aug 16 12:36:01 UTC 2024
Build Hash: 81c8b64b61d93520e731b86189000280082950f6
Build Enterprise Ready: true
```

**Comment by champsupertramp** [comment]
Hi @dmitrijkir  just checking if have tested this plugin to latest version 9.11.1?

Kindest Regards,

**Comment by dmitrijkir** [comment]
Hi, no, I haven't tested it with version 9.11. Have you tried installing any other plugins? Do they install correctly?

**Comment by champsupertramp** [comment]
Hi @dmitrijkir  - turns out it was a directory permission issue. I am closing this issue now.

Found another issue in this ticket: https://github.com/dmitrijkir/mattermost-plugin-calendar/issues/29
